---
title: "homework_7"
author: "Holden Mitchell"
date: "10/22/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Homework 7

7-1,2,3,4,5, 7-7, 7-16, 7-27, 7-53 (need R codes if available)
Make sure Power Curve works (need codes and graph)
Practice Calculating Beta (pp. 246-248)(need PowerPoint slides to present in class)

##### 7-1

Ho: /mu/ <= $3.75
H1: /mu/ > $3.75

##### 7-2

##### 7-3

Ho: p = 0.8
H1: p != 0.8

##### 7-4

##### 7-5

Ho: u <= 12
H1: u > 12

##### 7-7

a. Null, there are no weapons
b. Type I error: rejuecting the null hypothesis and concluding there are weapons when there are no weapons
c. Type II error would be more costly in terms of endangering lives. Type I would just be an inconvenience for the passenger.
d. Largest value of /alpha/ possible.
e. If the sensitivity of the detectors is increased
f. If /alpha/ is to be increased, then the sensitivity of the dectectors should also be increased to compensate for the higher

##### 7-16

##### 7-27

a. geographical differences, cultural differences, income differences.
b. depending on the number of breakdowns, one sample may not be large enough
c. t = 25.8415, p-value= 0.000 Reject at both /alpha/
d. t = 70.7107, Teject at both /alpha/
e. t = 56.8458, Reject at both /alpha/
f. t = very large, Reject at both /alpha/
g. t = -8.2292, Teject at both /alpha/

##### 7-53

Ho: u >= 50
H1: u < 50
t = -3.009, Reject Ho